"""changed models tables

Revision ID: 371fa0b3fba2
Revises: 32c97c1aac39
Create Date: 2024-10-15 16:17:38.035803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371fa0b3fba2'
down_revision: Union[str, None] = '32c97c1aac39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'filter', ['name'])
    op.add_column('patent', sa.Column('appl_number', sa.String(), nullable=True))
    op.add_column('patent', sa.Column('patent_starting_date', sa.Date(), nullable=True))
    op.add_column('patent', sa.Column('publication_url', sa.String(length=255), nullable=True))
    op.drop_column('patent', 'category')
    op.add_column('person', sa.Column('okopf', sa.String(), nullable=True))
    op.add_column('person', sa.Column('okvad', sa.String(), nullable=True))
    op.add_column('person', sa.Column('region', sa.String(), nullable=True))
    op.add_column('person', sa.Column('uk', sa.SmallInteger(), nullable=False, comment='Участник кластера(uk=1-участник, uk=0-нет)'))
    op.add_column('person', sa.Column('support_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'support_type')
    op.drop_column('person', 'uk')
    op.drop_column('person', 'region')
    op.drop_column('person', 'okvad')
    op.drop_column('person', 'okopf')
    op.add_column('patent', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patent', 'publication_url')
    op.drop_column('patent', 'patent_starting_date')
    op.drop_column('patent', 'appl_number')
    op.drop_constraint(None, 'filter', type_='unique')
    # ### end Alembic commands ###
