"""added new field in person model(ogrn)

Revision ID: 7d06af269385
Revises: 371fa0b3fba2
Create Date: 2024-10-31 17:30:23.353280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d06af269385'
down_revision: Union[str, None] = '371fa0b3fba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patent', 'patent_starting_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('person', sa.Column('ogrn', sa.String(), nullable=False, comment='ОГРН организации'))
    op.create_unique_constraint(None, 'person', ['ogrn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'ogrn')
    op.alter_column('patent', 'patent_starting_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
